// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0_ipgGhMlUwFtxux6mGj748Yi99OGeg',
    appId: '1:921544311332:web:fed781e79b25f90865ceb1',
    messagingSenderId: '921544311332',
    projectId: 'voskcoin-55f3a',
    authDomain: 'voskcoin-55f3a.firebaseapp.com',
    storageBucket: 'voskcoin-55f3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1I85MK4XNgoqJUZEZQmLXmo1pvDdKl1s',
    appId: '1:921544311332:android:2db3811a11a3a85d65ceb1',
    messagingSenderId: '921544311332',
    projectId: 'voskcoin-55f3a',
    storageBucket: 'voskcoin-55f3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtiXvZV1k7x3XFduC7syi9TcAn5a7K80',
    appId: '1:921544311332:ios:7b94b39add7a00f765ceb1',
    messagingSenderId: '921544311332',
    projectId: 'voskcoin-55f3a',
    storageBucket: 'voskcoin-55f3a.appspot.com',
    iosClientId: '921544311332-bh93tb141ejp9dg9a4j9kt1jt2komrb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.voskcoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtiXvZV1k7x3XFduC7syi9TcAn5a7K80',
    appId: '1:921544311332:ios:7b94b39add7a00f765ceb1',
    messagingSenderId: '921544311332',
    projectId: 'voskcoin-55f3a',
    storageBucket: 'voskcoin-55f3a.appspot.com',
    iosClientId: '921544311332-bh93tb141ejp9dg9a4j9kt1jt2komrb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.voskcoin',
  );
}
